### ISSUE TITLE
oe_theme dependency

### ISSUE THREAD

**Issue by timpevi** [openeuropa/oe_profile#41]
Hello, 

is it possible to update the dependency to the latest version of oe_theme 3.1.1?

V.

**Comment by LOBsTerr** [comment]
We faced the same issue sometime ago, when I tried to migrate to php 8.1. Now, as a migration plan to Drupal 10, we faced it again. We depend on oe_profile, which still has dependency on the old oe_theme version. Please release a new version of oe_profile, with updated dependencies

**Comment by brummbar** [comment]
Hi @timpevi, @LOBsTerr . oe_profile is not anymore maintained, and we discourage using it as it offers little to no benefits.
The only thing it was meant to do was to have a dependency on oe_theme, but now that OpenEuropa has multiple themes, it makes less sense to have it.
We recommend you create your own profile or move to the minimal installation profile.
You can use https://www.drupal.org/project/profile_switcher to switch to another profile.

**Comment by brummbar** [comment]
We made another release with #44 .
